// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDioOJNFlpoRWRJaCT7PqNDFb52e_TpnXg',
    appId: '1:804750076269:web:77270f9576f159b5945264',
    messagingSenderId: '804750076269',
    projectId: 'ez-notes-41e7f',
    authDomain: 'ez-notes-41e7f.firebaseapp.com',
    databaseURL:
        'https://ez-notes-41e7f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ez-notes-41e7f.appspot.com',
    measurementId: 'G-BG9CY61S9L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8h26yRB9rMvE92dOOm6uptoL5fJckbdQ',
    appId: '1:804750076269:android:3fa6365908e82ec1945264',
    messagingSenderId: '804750076269',
    projectId: 'ez-notes-41e7f',
    databaseURL:
        'https://ez-notes-41e7f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ez-notes-41e7f.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8h26yRB9rMvE92dOOm6uptoL5fJckbdQ',
    appId: '1:804750076269:web:77270f9576f159b5945264',
    messagingSenderId: '804750076269',
    projectId: 'ez-notes-41e7f',
  );
}
